### ISSUE TITLE
Teachnook

### ISSUE THREAD

**Issue by Pravin-P-Singh** [NikunjaSarma/CPP_programs#1]
Hi nikunj, I found your profile via the live lecture of teachnook. I want to have conversation regarding the assignments and project can you drop your email or any social account through which i can connect?

**Comment by NikunjaSarma** [comment]
Yes sir you can text me on WhatsApp
https://wa.me/message/DXBBN3KCV6IPH1?src=qr

**Comment by NikunjaSarma** [comment]
Ya @Pravin-P-Singh , you can Contact me on ig: @image_alche.my
